import { useEffect, useId, useMemo, useRef, useState } from "react";

import CostBreakdownChart from "./CostBreakdownChart";
import {
  DEFAULT_WORKFLOW,
  MODEL_PRESETS,
  OPERATION_META,
  formatTokens,
  formatUsd,
  simulate,
  type ModelConfig,
  type SimulationResult,
  type WorkflowShape,
} from "./simulation";

const DEFAULT_MODEL = "Claude Opus 4.8";
const CONTROL_HELP = {
  modelPreset:
    "Loads this model's token prices and minimum cacheable prompt size.",
  uncachedInput:
    "Cost per million prompt tokens processed normally, without a cache discount.",
  cachedInput: "Cost per million matching prompt tokens reused from cache.",
  cacheWrite:
    "Cost per million prompt tokens stored so later calls can reuse them.",
  output:
    "Cost per million tokens generated by the model. Output is always billed separately.",
  userTurns: "Number of user messages in the simulated conversation.",
  toolCallsPerTurn:
    "Number of tool exchanges completed after each user message.",
  toolContextTokens:
    "Average tokens added to the prompt context by each tool result. Larger values simulate heavy tools like file reads; smaller values simulate quick lookups.",
  cacheEnabled:
    "When enabled, matching prior prompt tokens use cached-input pricing and new prompt tokens use cache-write pricing. When disabled, every call reprocesses its full prompt at the uncached-input price.",
} as const;

function InfoTooltip({ label, text }: { label: string; text: string }) {
  const tooltipId = useId();
  const [hoverOpen, setHoverOpen] = useState(false);
  const [touchOpen, setTouchOpen] = useState(false);
  const isOpen = hoverOpen || touchOpen;
  const rootRef = useRef<HTMLSpanElement>(null);
  const buttonRef = useRef<HTMLButtonElement>(null);

  useEffect(() => {
    if (!touchOpen) return;
    const handlePointerDown = (e: PointerEvent) => {
      if (!rootRef.current?.contains(e.target as Node)) {
        setTouchOpen(false);
        buttonRef.current?.blur();
      }
    };
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        setTouchOpen(false);
        buttonRef.current?.blur();
      }
    };
    document.addEventListener("pointerdown", handlePointerDown);
    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("pointerdown", handlePointerDown);
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [touchOpen]);

  return (
    <span ref={rootRef} className="relative inline-flex shrink-0">
      <button
        ref={buttonRef}
        type="button"
        aria-label={`More information about ${label}`}
        aria-describedby={tooltipId}
        aria-expanded={touchOpen}
        className="size-5 cursor-help rounded-full border border-border text-xs font-semibold text-foreground/65 focus:outline-2 focus:outline-accent"
        onMouseEnter={() => setHoverOpen(true)}
        onMouseLeave={() => setHoverOpen(false)}
        onFocus={() => setHoverOpen(true)}
        onBlur={() => setHoverOpen(false)}
        onPointerUp={e => {
          if (e.pointerType === "touch") {
            e.preventDefault();
            setTouchOpen(o => !o);
          }
        }}
      >
        i
      </button>
      <span
        id={tooltipId}
        role="tooltip"
        className={`pointer-events-none absolute bottom-full left-1/2 z-30 mb-2 w-64 max-w-[calc(100vw-2rem)] -translate-x-1/2 rounded border border-border bg-background p-2 text-xs leading-relaxed text-foreground shadow-lg ${isOpen ? "block" : "hidden"}`}
      >
        {text}
      </span>
    </span>
  );
}

function FieldLabel({ label, help }: { label: string; help: string }) {
  return (
    <span className="flex items-center gap-1.5">
      <span>{label}</span>
      <InfoTooltip label={label} text={help} />
    </span>
  );
}

function NumberField({
  label,
  help,
  value,
  onChange,
}: {
  label: string;
  help: string;
  value: number;
  onChange: (value: number) => void;
}) {
  const inputId = useId();
  return (
    <div className="grid min-w-0 gap-1 text-sm">
      <div className="flex items-center gap-1.5">
        <label htmlFor={inputId}>{label}</label>
        <InfoTooltip label={label} text={help} />
      </div>
      <span className="flex min-w-0 items-center rounded border border-border bg-background px-2 focus-within:outline-2 focus-within:outline-accent">
        <span className="text-foreground/60">$</span>
        <input
          id={inputId}
          className="min-w-0 flex-1 bg-transparent px-2 py-1.5 outline-none"
          type="number"
          min={0}
          step={0.05}
          value={value}
          onChange={event => onChange(Math.max(0, Number(event.target.value)))}
        />
      </span>
    </div>
  );
}

function Slider({
  label,
  help,
  value,
  min,
  max,
  step = 1,
  suffix = "",
  onChange,
}: {
  label: string;
  help: string;
  value: number;
  min: number;
  max: number;
  step?: number;
  suffix?: string;
  onChange: (value: number) => void;
}) {
  const inputId = useId();
  return (
    <div className="grid gap-1 text-sm">
      <div className="flex justify-between gap-3">
        <div className="flex items-center gap-1.5">
          <label htmlFor={inputId}>{label}</label>
          <InfoTooltip label={label} text={help} />
        </div>
        <output className="tabular-nums" htmlFor={inputId}>
          {value}
          {suffix}
        </output>
      </div>
      <input
        id={inputId}
        className="w-full accent-accent"
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={event => onChange(Number(event.target.value))}
      />
    </div>
  );
}

function PricingControls({
  model,
  selectedPreset,
  onChange,
}: {
  model: ModelConfig;
  selectedPreset: string | null;
  onChange: (model: ModelConfig) => void;
}) {
  const fields = [
    ["uncachedInputPerM", "Base (Uncached) Input", CONTROL_HELP.uncachedInput],
    ["cachedInputPerM", "Cache Read", CONTROL_HELP.cachedInput],
    ["cacheWritePerM", "Input + Cache Write", CONTROL_HELP.cacheWrite],
    ["outputPerM", "Output", CONTROL_HELP.output],
  ] as const;
  return (
    <section className="space-y-3">
      <div>
        <h3 className="text-base font-semibold">Pricing</h3>
        <p className="text-sm text-foreground/70">Dollars per million tokens</p>
      </div>
      <div>
        <div className="mb-2 text-sm font-medium">
          <FieldLabel label="Model preset" help={CONTROL_HELP.modelPreset} />
        </div>
        <div className="flex flex-wrap gap-2" aria-label="Model presets">
          {Object.entries(MODEL_PRESETS).map(([name, preset]) => (
            <button
              key={name}
              type="button"
              className={`rounded-full border border-border px-3 py-1 text-sm transition-colors hover:bg-muted ${selectedPreset === name ? "bg-accent text-background" : "bg-background"}`}
              aria-pressed={selectedPreset === name}
              onClick={() => onChange({ ...preset })}
            >
              {name}
            </button>
          ))}
        </div>
      </div>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        {fields.map(([key, label, help]) => (
          <NumberField
            key={key}
            label={label}
            help={help}
            value={model[key]}
            onChange={value => onChange({ ...model, [key]: value })}
          />
        ))}
      </div>
    </section>
  );
}

function WorkflowControls({
  shape,
  onChange,
}: {
  shape: WorkflowShape;
  onChange: (shape: WorkflowShape) => void;
}) {
  return (
    <section className="space-y-3">
      <div>
        <h3 className="text-base font-semibold">Workflow</h3>
        <p className="text-sm text-foreground/70">
          Conversation shape and tool activity
        </p>
      </div>
      <div className="grid gap-4 rounded border border-border p-3 sm:grid-cols-2">
        <Slider
          label="User turns"
          help={CONTROL_HELP.userTurns}
          value={shape.userTurns}
          min={1}
          max={10}
          onChange={userTurns => onChange({ ...shape, userTurns })}
        />
        <Slider
          label="Tool calls per turn"
          help={CONTROL_HELP.toolCallsPerTurn}
          value={shape.toolCallsPerTurn}
          min={0}
          max={40}
          onChange={toolCallsPerTurn =>
            onChange({ ...shape, toolCallsPerTurn })
          }
        />
        <Slider
          label="Tool context tokens"
          help={CONTROL_HELP.toolContextTokens}
          value={shape.toolContextTokens}
          min={0}
          max={5000}
          step={10}
          suffix=" tok"
          onChange={toolContextTokens =>
            onChange({ ...shape, toolContextTokens })
          }
        />
      </div>
    </section>
  );
}

function CacheControl({
  enabled,
  onChange,
}: {
  enabled: boolean;
  onChange: (enabled: boolean) => void;
}) {
  return (
    <section className="border-t border-border pt-4">
      <div className="flex items-center justify-between gap-4 rounded border border-border bg-background px-3 py-2">
        <FieldLabel label="Enable cache" help={CONTROL_HELP.cacheEnabled} />
        <button
          type="button"
          role="switch"
          aria-checked={enabled}
          aria-label="Enable cache"
          className={`relative h-6 w-11 shrink-0 rounded-full border transition-colors focus:outline-2 focus:outline-accent ${enabled ? "border-accent bg-accent" : "border-border bg-muted"}`}
          onClick={() => onChange(!enabled)}
        >
          <span
            className={`absolute top-0.5 left-0.5 size-4 rounded-full bg-background shadow-sm transition-transform ${enabled ? "translate-x-5" : ""}`}
          />
        </button>
      </div>
    </section>
  );
}

function TotalSummary({
  result,
  cachedResult,
  uncachedResult,
  cacheEnabled,
  userTurns,
}: {
  result: SimulationResult;
  cachedResult: SimulationResult;
  uncachedResult: SimulationResult;
  cacheEnabled: boolean;
  userTurns: number;
}) {
  const savings =
    uncachedResult.totalCost === 0
      ? 0
      : ((uncachedResult.totalCost - cachedResult.totalCost) /
          uncachedResult.totalCost) *
        100;
  const comparison =
    savings >= 0
      ? `cache saves ${Math.abs(savings).toFixed(0)}%`
      : `cache costs ${Math.abs(savings).toFixed(0)}% more`;
  return (
    <section className="grid gap-4 rounded border border-border p-3">
      <div className="grid gap-4 sm:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]">
        <div>
          <p className="text-xs text-foreground/65 uppercase">Total cost</p>
          <p className="mt-1 text-2xl font-bold text-accent tabular-nums">
            {formatUsd(result.totalCost)}
          </p>
          <p className="mt-1 text-xs text-foreground/70">
            {cacheEnabled
              ? `${formatUsd(result.totalCost)} with cache · ${formatUsd(uncachedResult.totalCost)} without · ${comparison}`
              : `${formatUsd(result.totalCost)} without cache · ${formatUsd(cachedResult.totalCost)} with · ${comparison}`}
          </p>
        </div>
        <div>
          <p className="text-xs text-foreground/65 uppercase">Cost split</p>
          <div className="mt-3 flex h-3 overflow-hidden rounded-sm bg-muted">
            {result.operations.map(operation => (
              <span
                key={operation}
                className={OPERATION_META[operation].swatchClass}
                style={{
                  width: `${result.totalCost === 0 ? 0 : (result.totalCostByOperation[operation] / result.totalCost) * 100}%`,
                }}
              />
            ))}
          </div>
          <div className="mt-2 flex flex-wrap gap-x-3 gap-y-1 text-xs">
            {result.operations.map(operation => (
              <span key={operation}>
                {OPERATION_META[operation].label}{" "}
                {result.totalCost === 0
                  ? "0"
                  : (
                      (result.totalCostByOperation[operation] /
                        result.totalCost) *
                      100
                    ).toFixed(0)}
                %
              </span>
            ))}
          </div>
        </div>
      </div>
      <dl className="grid grid-cols-2 gap-3 border-t border-border pt-3 text-sm sm:grid-cols-3">
        <div>
          <dt className="text-foreground/65">User turns</dt>
          <dd className="font-semibold tabular-nums">{userTurns}</dd>
        </div>
        <div>
          <dt className="text-foreground/65">LLM calls</dt>
          <dd className="font-semibold tabular-nums">{result.calls.length}</dd>
        </div>
        <div>
          <dt className="text-foreground/65">Uncached input tokens</dt>
          <dd className="font-semibold tabular-nums">
            {formatTokens(result.totalTokensByOperation.uncachedInput)}
          </dd>
        </div>
        <div>
          <dt className="text-foreground/65">Cache write tokens</dt>
          <dd className="font-semibold tabular-nums">
            {formatTokens(result.totalTokensByOperation.cacheWrite)}
          </dd>
        </div>
        <div>
          <dt className="text-foreground/65">Cache read tokens</dt>
          <dd className="font-semibold tabular-nums">
            {formatTokens(result.totalTokensByOperation.cachedInput)}
          </dd>
        </div>
        <div>
          <dt className="text-foreground/65">Output tokens</dt>
          <dd className="font-semibold tabular-nums">
            {formatTokens(result.totalTokensByOperation.output)}
          </dd>
        </div>
      </dl>
    </section>
  );
}

const cloneShape = (shape: WorkflowShape): WorkflowShape => ({
  ...shape,
  reasoning: { ...shape.reasoning },
});

export default function AgentPricingSimulator() {
  const [model, setModel] = useState<ModelConfig>({
    ...MODEL_PRESETS[DEFAULT_MODEL],
  });
  const [shape, setShape] = useState(() => cloneShape(DEFAULT_WORKFLOW));
  const [cacheEnabled, setCacheEnabled] = useState(true);
  const cachedResult = useMemo(
    () => simulate(model, shape, { cacheEnabled: true }),
    [model, shape]
  );
  const uncachedResult = useMemo(
    () => simulate(model, shape, { cacheEnabled: false }),
    [model, shape]
  );
  const result = cacheEnabled ? cachedResult : uncachedResult;
  const selectedModel =
    Object.entries(MODEL_PRESETS).find(([, preset]) =>
      Object.entries(preset).every(
        ([key, value]) => model[key as keyof ModelConfig] === value
      )
    )?.[0] ?? null;

  return (
    <div className="my-8 space-y-5 rounded-lg border border-border bg-background p-4 text-foreground">
      <header>
        <h2 className="text-xl font-bold">Coding-agent pricing simulator</h2>
        <p className="mt-1 text-sm text-foreground/70">
          Shape a conversation and compare cached and uncached LLM call costs.
        </p>
      </header>
      <PricingControls
        model={model}
        selectedPreset={selectedModel}
        onChange={setModel}
      />
      <WorkflowControls shape={shape} onChange={setShape} />
      <CacheControl enabled={cacheEnabled} onChange={setCacheEnabled} />
      <section className="space-y-5 border-t border-border pt-4">
        <h3 className="text-base font-semibold">Results</h3>
        <TotalSummary
          result={result}
          cachedResult={cachedResult}
          uncachedResult={uncachedResult}
          cacheEnabled={cacheEnabled}
          userTurns={shape.userTurns}
        />
        <CostBreakdownChart result={result} />
      </section>
      <p className="border-t border-border pt-3 text-xs leading-relaxed text-foreground/60">
        Provider-specific TTLs, routing misses, cache breakpoints, and block
        lookback are not modeled.
      </p>
    </div>
  );
}
